### ISSUE TITLE
Smile\DebugToolbar\Plugin\App\Cache not found after uninstall

### ISSUE THREAD

**Issue by AboElnoor** [Smile-SA/magento2-module-debug-toolbar#19]
After running `bin/magento module:uninstall Smile_DebugToolbar`

I keep getting the following exception everywhere:

```
Class Smile\DebugToolbar\Plugin\App\Cache does not exist#0 vendor/magento/framework/Code/Reader/ClassReader.php(34): ReflectionClass->__construct()
#1vendor/magento/framework/ObjectManager/Definition/Runtime.php(54): Magento\Framework\Code\Reader\ClassReader->getConstructor()
#2 vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(48): Magento\Framework\ObjectManager\Definition\Runtime->getParameters()
#3 vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create()
#4vendor/magento/framework/Interception/PluginList/PluginList.php(174): Magento\Framework\ObjectManager\ObjectManager->get()
#5 vendor/magento/framework/Interception/Interceptor.php(133): Magento\Framework\Interception\PluginList\PluginList->getPlugin()
#6 vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\Cache\Interceptor->Magento\Framework\Interception\{closure}()
#7 generated/code/Magento/Framework/App/Cache/Interceptor.php(32): Magento\Framework\App\Cache\Interceptor->___callPlugins()
#8 vendor/magento/framework/App/Cache/Proxy.php(67): Magento\Framework\App\Cache\Interceptor->load()
#9 vendor/magento/framework/App/ProductMetadata.php(78): Magento\Framework\App\Cache\Proxy->load()
#10 vendor/magento/framework/Console/Cli.php(98): Magento\Framework\App\ProductMetadata->getVersion()
#11 bin/magento(22): Magento\Framework\Console\Cli->__construct()
#12 {main}

```

I cleared the Redis cache and env file, searched the whole database and the code for this, and found nothing.

This took me a lot of time to find `var/smile_toolbar` directory which needs to be removed to make everything work fine.

I believe it's something needs to be mentioned in the readme file which may save a lot of time for the other developers.

**Comment by guvra** [comment]
Hi,

I don't think this directory was the cause of your fatal error.

The stacktrace shows that the plugins of the module were still registered after the uninstallation of the module (probably a cache issue?)

**Comment by AboElnoor** [comment]
Hi,
I tried everything, I cleared every possible cache and directory. the issue solved only after deleting this directory

**Comment by guvra** [comment]
The uninstallation procedure was updated in commit 237bb5e.
